apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/vketest/http-oayxl:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/vketest/http-oayxl:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: http-oayxl
        chartPath: charts/http-oayxl
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/vketest/http-oayxl"
          image.tag: "{{.DIGEST_HEX}}"
